version: '3.9'

services:
  app:
    build:
      context: ./
      dockerfile: ./build/Dockerfile
    ports:
      - "8082:8082"
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    networks:
      - network
  postgres:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    volumes:
      - expression-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=expression_user
      - POSTGRES_PASSWORD=expression_password
      - POSTGRES_DB=expression_db
    networks:
      - network
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6377:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - expression-volume:/root/redis
    networks:
      - network
networks:
  network:
    driver: bridge
    name: expression-network
volumes:
  expression-volume: